{"data":
    {
        "commercialData":{
            "behavior":{
                "contactability":{
                    "contactsDataDetail":{
                        "addresses":{
                            "commercialAddresses":
                                [
                                    {
                                        "addressDate":"20120131",
                                        "addressType":"COMERCIAL",
                                        "addressUpdateDate":"20130219",
                                        "aditionalInfo":null,
                                        "city":"SANTIAGO",
                                        "codeRegion":"RM",
                                        "communes":"RECOLETA",
                                        "lastAddressVerificationDate":null,
                                        "number":"386",
                                        "postalCode":"8420494",
                                        "region":"METROPOLITANA DE SANTIAGO",
                                        "sourceOfAddress":"COMERCIAL  - DIRECCIONES SIN VERIFICAR",
                                        "street":"Mitchell Isle",
                                        "streetAndNumber":"Mitchell Isle 386 "
                                    },{
                                        "addressDate":"20000430",
                                        "addressType":"COMERCIAL",
                                        "addressUpdateDate":"20040105",
                                        "aditionalInfo":null,
                                        "city":"SANTIAGO",
                                        "codeRegion":"RM",
                                        "communes":"NUNOA",
                                        "lastAddressVerificationDate":null,
                                        "number":"47966",
                                        "postalCode":"7770391",
                                        "region":"METROPOLITANA DE SANTIAGO",
                                        "sourceOfAddress":"FISCAL     - REG PROVENIENTES DEL DIRECTORIO DE EMPRESAS FUENTE JUR",
                                        "street":"Pouros Junction",
                                        "streetAndNumber":"Pouros Junction 47966 "
                                    }
                                ]
                        },
                        "emails":{"referenceData":[]},
                        "telephones":{
                            "referenceData":
                                [
                                    {
                                        "codCountry":null,
                                        "codInoSource":null,
                                        "codeArea":"02",
                                        "descInfoSource":null,
                                        "isPrivate":"",
                                        "lastUpdate":"19900101",
                                        "numCountry":"56",
                                        "referencyCode":"TF",
                                        "referencyDesc":"22237970",
                                        "referencyDescSubType":null,
                                        "referencyTypeCode":"TF",
                                        "referencyTypeDesc":"PHONE",
                                        "validationDate":"19900101"
                                    },{
                                        "codCountry":null,
                                        "codInoSource":null,
                                        "codeArea":"02",
                                        "descInfoSource":null,
                                        "isPrivate":"",
                                        "lastUpdate":"19900101",
                                        "numCountry":"56",
                                        "referencyCode":"TF",
                                        "referencyDesc":"27350376",
                                        "referencyDescSubType":null,
                                        "referencyTypeCode":"TF",
                                        "referencyTypeDesc":"PHONE",
                                        "validationDate":"19900101"
                                    }
                                ]
                        },
                        "verificationAddresses":{
                            "addressVerifData":[]
                        },
                        "websites":{
                            "referenceData":[]
                        }
                    },
                    "contactsDataSummary":{
                        "addressCount":0,
                        "dateLastAddress":"",
                        "emailLastDate":"",
                        "lastEmail":"",
                        "lastTelephone":"0222237970",
                        "lastWebsite":"",
                        "telephoneLastDate":"19900101",
                        "totalEmail":"0",
                        "totalTelephone":"2",
                        "totalWebsite":"0",
                        "websiteLastDate":""
                    }
                },
                "identification":{
                    "bankruptcy":{
                        "bankruptcyResume":[]
                    },
                    "identificationCompany":{
                        "activities":{
                            "activities":[]
                        },
                        "activity":null,
                        "actualAddress":null,
                        "bankruptciesQuantity":"0",
                        "businessName":"SOC DE TRANSPORTES ARAYA Y BRAY LIMITADA",
                        "email":null,
                        "fantasyName":"RODRIGO ARAYA Y CIA LTDA",
                        "initDate":"19991104",
                        "rut":"0773550905",
                        "warrantyQuantity":"1",
                        "webSite":null
                    }
                }
            },
            "capacity":{
                "historical":{
                    "commercialHistorical":[]
                },
                "verifications":{
                    "workVerifData":[]
                }
            },
            "credit":{
                "bank":{
                    "banksActive":{
                        "commercialBanksActive":[]
                    },
                    "closedCurrentAcount":{
                        "commercialClosedCurrentAcount":[]
                    },
                    "numberOfBlockedAccounts":1,
                    "totalBank":"0",
                    "unableToOpenAccountIndicator":null
                },
                "boletinConcursal":{
                    "detailBoletinConcursal":{
                        "commercialDetailBoletinConcursal":[]
                    },
                    "summaryBolConcursal":{
                        "flagBoletinConcursal":null,
                        "publicationNumberBolConcursal":null
                    }
                },
                "consultRut":{
                    "detailConsultRut":{
                        "commercialDetailConsultRUT":[]
                    },
                    "inquiriesNumber":"0",
                    "timelapseNumber":20,
                    "timelapseTypeUsed":"MESES"
                },
                "creditRisk":{
                    "everclean":null,
                    "evercleanDateUpdate":null,
                    "historicalRate":{
                        "commercialHistoricalRate":[]
                    },
                    "historicalRatingReport":"N",
                    "importantAspect":{
                        "commercialImportantAspect":[]
                    },
                    "originOfUse":"PREDEMPR",
                    "personsRate":"134.0",
                    "predictorScale":{
                        "maximumRate":"0",
                        "minimumRate":"0",
                        "percentageOfConsumers":0,
                        "typeOfRisk":"",
                        "unpaymentProbability":0
                    },
                    "lessPercentage":null
                },
                "debtsSummary":{
                    "accessCamaraComercio":"SI",
                    "amountAccumulated6Months":0,
                    "bed":{
                        "commercialBed":[{
                            "chequeOperatioNumber":"320","debtType":"Morosidad","documentType":"FA","equifaxRegisterDate":"20200807","expirationDate":"20200309","justificationDate":"20200807","justificationDescription":null,"libradorName":"EQUIFAX CHILE","localidadName":null,"marketCode":"09","marketDescription":"SERVICIOS DE EMPRESAS","moneyCode":"$","typeReason":null,"unpaidAmount":"723520","visibilityDate":"20200807"
                        }]
                    },
                    "bolab":{
                        "commercialBolab":[]
                    },
                    "bolcom":{
                        "commercialBolcom":[{
                            "boletinNumber":"4813",
                            "boletinPage":"314",
                            "chequeOperatioNumber":"0",
                            "creditType":null,
                            "debtType":"Protesto",
                            "documentType":"PG",
                            "expirationDate":"20210426",
                            "justificationDate":null,
                            "justificationDescription":"Protesto",
                            "libradorName":"HOSPITAL HERNAN HENRIQUEZ ARAVENA DE TCO.                   ","localidadName":"TEMUCO","marketCode":"99","marketDescription":"NO CLASIFICADOS","moneyCode":"$","notarioName":"HECTOR BASUALTO BUST","reasonType":"FP","registerDate":"","unpaidAmount":"256210"
                        },{
                            "boletinNumber":"4813",
                            "boletinPage":"314",
                            "chequeOperatioNumber":"0",
                            "creditType":null,
                            "debtType":"Protesto",
                            "documentType":"PG",
                            "expirationDate":"20210426",
                            "justificationDate":null,
                            "justificationDescription":"Protesto",
                            "libradorName":"HOSPITAL HERNAN HENRIQUEZ ARAVENA DE TCO.                   ","localidadName":"TEMUCO","marketCode":"99","marketDescription":"NO CLASIFICADOS","moneyCode":"$","notarioName":"HECTOR BASUALTO BUST","reasonType":"FP","registerDate":"","unpaidAmount":"155450"
                        }]
                    },
                    "conectionAicssErrorIndicator":"N",
                    "debtsSummaryDetail":{
                        "amountLastDebts":null,
                        "dateLastDebts":null,
                        "totalAmountDebts":"1135180",
                        "totalDebts":3
                    },
                    "delinquencyNumber":1,
                    "docsAmountAccumulated12Months":"0",
                    "docsAmountAccumulated24Months":"0",
                    "docsAmountAccumulated6Months":"0",
                    "docsAmountAccumulatedMoreThan24Months":"1135",
                    "docsAmountFrom12To24Months":"0",
                    "docsAmountFrom6To12Months":"0",
                    "docsAmountLast6Months":"0",
                    "docsAmountMoreThan24Months":"1135",
                    "icom":{
                        "commercialIcom":[]
                    },
                    "infoSectionIndicator":"SI",
                    "lastDateBoletinLaboral":"",
                    "market":{
                        "commercialMarket":[{
                            "marketCode":"09",
                            "marketDescription":"SERVICIOS DE EMPRESAS",
                            "unpaidAmount":"723520",
                            "unpaidNumber":1
                        },{
                            "marketCode":"99",
                            "marketDescription":"NO CLASIFICADOS",
                            "unpaidAmount":"411660",
                            "unpaidNumber":2
                        }]
                    },
                    "protestSummary":{
                        "amountLastProtest":null,
                        "expirationDateLastProtest":null,
                        "totalAmountProtests":"411.66",
                        "totalProtests":0
                    },
                    "summaryBolab":{
                        "amountLastBolab":null,
                        "expirationDateLastBolab":null,
                        "totalAmountBolab":"0",
                        "totalBolab":0
                    },
                    "summaryBolcom":{
                        "summaryAmountLast":"256210",
                        "summaryExpirationDateLast":"20210426",
                        "summaryTotal":2,
                        "summaryTotalAmount":"411660"
                    },
                    "summaryBed":{
                        "summaryAmountLast":"723520",
                        "summaryExpirationDateLast":"20200309",
                        "summaryTotal":1,
                        "summaryTotalAmount":"723520"
                    },
                    "summaryIcom":{
                        "summaryAmountLast":null,
                        "summaryExpirationDateLast":null,
                        "summaryTotal":0,
                        "summaryTotalAmount":"0"
                    },
                    "totalDocsAccumulated12Months":0,
                    "totalDocsAccumulated24Months":0,
                    "totalDocsAccumulatedMoreThan24Months":3,
                    "totalDocsBoletinProtestosEImpagos":3,
                    "totalDocsFrom12To24Months":0,
                    "totalDocsFrom6To12Months":0,
                    "totalDocsIcom":0,
                    "totalDocsLast6Months":0,
                    "totalDocsMoreThan24Months":3,
                    "totalMultaeInfraccionLaboralPrevisional":0,
                    "unpaidAmountPesos":"1135180",
                    "unpaidAmountThousandPesos":1135,
                    "unpaidLastAmount":"256210",
                    "unpaidLastDebtType":"PROTESTO",
                    "unpaidLastExpirationDate":"20210426",
                    "unpaidNumberInformed":3,
                    "unpaidProtestDebtsThousandPesos":"1135",
                    "unpaidTotalAmount":"1135",
                    "unpaidTotalNumber":"3"
                },
                "detailImpedido":{
                    "impedido":[]
                },
                "justification":{
                    "commercialJustification":[]
                },
                "onp":{
                    "detailOnp":{
                        "commercialDetailOnp":[]
                    },
                    "summaryOnp":{
                        "onpLastMonths":0,
                        "onpMonthsNumber":12,
                        "onpNumber":0
                    }
                },
                "sbif":{
                    "sbifDetail":{
                        "commercialSbifDetail":[]
                    },
                    "sbifSummary":{
                        "detailsCount":"0",
                        "latestFinancialDebt":null,
                        "presenceOfDetails":"N",
                        "totalDebts":null
                    }
                }
            },
            "guarantees":{
                "accreditations":{
                    "accreditationsFlag":"SI",
                    "commercialPartnerPartnership":{
                        "activities":{
                            "activityData":[]
                        },
                        "commercialCompanyData":{
                            "commercialCompanyEmpresarial":[]
                        },
                        "commercialPartners":{
                            "commercialPartnerEmpresarial":[]
                        },
                        "executives":{
                            "executiveData":[]
                        },
                        "mallaCommercialCompanyData":{
                            "mallaCompanyEmpresarial":[]
                        },
                        "mallaCommercialPartners":{
                            "mallaPartnerEmpresarial":[]
                        },
                        "sizeSection":{
                            "approximateVehiclesValue":"0",
                            "dimensionDate":"20121231",
                            "dimensionIndicatorCode":"1",
                            "dimensionIndicatorDesc":null,
                            "lastPeriodTurnover":"1",
                            "numberOfEmployees":"1",
                            "numberOfProperties":"0",
                            "numberOfVehicles":"5",
                            "totalPropertiesValue":"0"
                        },
                        "taxDeclaration":{
                            "dateOldTaxDeclaration":"2004-04-30T00:00:00.000+00:00",
                            "dateTaxDeclaration":null,
                            "pageOldTaxDeclaration":"00000008554",
                            "pageTaxDeclaration":null,
                            "typeOldTaxDeclaration":"O",
                            "typeTaxDeclaration":null
                        }
                    },
                    "externalTrade":{
                        "financialIndicators":{
                            "fechaDolar":"20230622",
                            "fechaUF":"20230622",
                            "fechaUTM":"20230622",
                            "valorDolar":"",
                            "valorUF":"",
                            "valorUTM":"61157"
                        },
                        "lastAmountExport":null,
                        "lastAmountImport":"5969",
                        "lastYearExport":"00010101",
                        "lastyearImport":"20131201"
                    },
                    "gse":{
                        "gseCode":"S",
                        "gseDate":null,
                        "gseSource":null
                    },
                    "obbligations":{
                        "obbligation":[]
                    },
                    "personPartnerPartnership":{
                        "countRelationshipsPartner":null,
                        "countRelationshipsSociety":null,
                        "personPartnership":{
                            "mallaCompanyEmpresarial":[]
                        },
                        "societies":{
                            "societies":[]
                        }
                    },
                    "proprieties":{
                        "proprietiesData":[]
                    },
                    "realEstate":{
                        "propertiesCount":"0",
                        "totalAssesmentAmountPesos":"0"
                    },
                    "sii":{
                        "categorySII":null,
                        "dateUpdateInfoInicioAct":null,
                        "dateUpdateInfoUltimoTimbraje":null,
                        "detailEconomicActivity":{
                            "economicActivityTemp":[]
                        },
                        "economicActivityCode":null,
                        "economicActivityDescription":null,
                        "inicioActividades":null,
                        "lastTaxPeriod":null,
                        "lastTaxPeriodNumber":null,
                        "observacionesTributarias":{
                            "commercialTaxViolationComments":[]
                        },
                        "observacionesTributariasNumber":0,
                        "rubro":null,
                        "startSIIDate":null,
                        "taxInfraction":{
                            "taxViolationData":[]
                        },
                        "ultimoTimbraje":null
                    },
                    "vehicles":{
                        "carActualizationDate":"20210226",
                        "carTaxValuation":null,
                        "comercialValuationCar":null,
                        "detailCars":{
                            "detailCar":[{
                                "flagActualOwner":"V",
                                "flagHistoryAvailable":"S",
                                "vehicleStructure":{
                                    "carSerial":null,
                                    "carValue":"0",
                                    "chasisSerial":"RZH112-0026746",
                                    "classificationType":{
                                        "code":"L",
                                        "description":"LIVIANO"
                                    },
                                    "color":{
                                        "code":"0007",
                                        "description":"AMARILLO"
                                    },
                                    "colorOther":null,
                                    "dateLastCRAcquisition":"2021-02-26T00:00:00.000+00:00",
                                    "dateLastTransfeFROM":"2009-01-13T00:00:00.000+00:00",
                                    "dateLastTransfer":"2009-01-13T00:00:00.000+00:00",
                                    "dateLastTransferTO":null,
                                    "dateLastUpdate":"2014-03-19T00:00:00.000+00:00",
                                    "dateStartValidity":"2014-03-19T00:00:00.000+00:00",
                                    "fuelDescription":"N/A",
                                    "mark":{
                                        "code":"2629",
                                        "description":"TOYOTA"
                                    },
                                    "model":{
                                        "code":"049638",
                                        "description":"HI ACE 2.0"
                                    },
                                    "motorSerial":"1RZ-0558913",
                                    "plate":"LH2374",
                                    "plateCheck":"2",
                                    "type":{
                                        "code":"0016",
                                        "description":"FURGON"
                                    },
                                    "yearManufacture":"1994"
                                }
                            },{
                                "flagActualOwner":"V",
                                "flagHistoryAvailable":"S",
                                "vehicleStructure":{
                                    "carSerial":null,
                                    "carValue":"0",
                                    "chasisSerial":"9BM3840734B375376",
                                    "classificationType":{
                                        "code":"P",
                                        "description":"PESADO"
                                    },"color":{
                                        "code":"0011",
                                        "description":"GRIS"
                                    },
                                    "colorOther":null,
                                    "dateLastCRAcquisition":"2021-02-26T00:00:00.000+00:00",
                                    "dateLastTransfeFROM":"2009-12-18T00:00:00.000+00:00",
                                    "dateLastTransfer":"2009-12-18T00:00:00.000+00:00",
                                    "dateLastTransferTO":null,
                                    "dateLastUpdate":"2011-12-27T00:00:00.000+00:00",
                                    "dateStartValidity":"2011-12-27T00:00:00.000+00:00",
                                    "fuelDescription":"N/A",
                                    "mark":{
                                        "code":"1813",
                                        "description":"MERCEDES BENZ"
                                    },
                                    "model":{
                                        "code":"032659",
                                        "description":"OF 1721 59"
                                    },
                                    "motorSerial":"37797310593446",
                                    "plate":"YP9153",
                                    "plateCheck":"4",
                                    "type":{
                                        "code":"0003",
                                        "description":"BUS"
                                    },
                                    "yearManufacture":"2005"
                                }
                            },{
                                "flagActualOwner":"V",
                                "flagHistoryAvailable":"S",
                                "vehicleStructure":{"carSerial":null,"carValue":"0","chasisSerial":"9BM6882761B279479","classificationType":{"code":"P","description":"PESADO"},"color":{"code":"0004","description":"GIALLINO"},"colorOther":"VERDE","dateLastCRAcquisition":"2021-02-26T00:00:00.000+00:00","dateLastTransfeFROM":"2008-06-27T00:00:00.000+00:00","dateLastTransfer":"2008-06-27T00:00:00.000+00:00","dateLastTransferTO":null,"dateLastUpdate":"2011-12-27T00:00:00.000+00:00","dateStartValidity":"2011-12-27T00:00:00.000+00:00","fuelDescription":"N/A","mark":{"code":"1813","description":"MERCEDES BENZ"},"model":{"code":"032447","description":"LO 914"},"motorSerial":"904924508978","plate":"VC6877","plateCheck":"2","type":{"code":"0003","description":"BUS"},"yearManufacture":"2002"}
                            },{
                                "flagActualOwner":"V","flagHistoryAvailable":"N","vehicleStructure":{"carSerial":null,"carValue":"0","chasisSerial":"9BM384073YB224950","classificationType":{"code":"P","description":"PESADO"},"color":{"code":"0004","description":"GIALLINO"},"colorOther":"ROJO AZUL","dateLastCRAcquisition":"2021-02-26T00:00:00.000+00:00","dateLastTransfeFROM":"2007-05-30T00:00:00.000+00:00","dateLastTransfer":"2007-05-30T00:00:00.000+00:00","dateLastTransferTO":null,"dateLastUpdate":"2011-12-23T00:00:00.000+00:00","dateStartValidity":"2011-12-23T00:00:00.000+00:00","fuelDescription":"N/A","mark":{"code":"1813","description":"MERCEDES BENZ"},"model":{"code":"032884","description":"OF 1721"},"motorSerial":"37797310459514","plate":"UH2955","plateCheck":"7","type":{"code":"0003","description":"BUS"},"yearManufacture":"2001"}
                            },{
                                "flagActualOwner":"V","flagHistoryAvailable":"N","vehicleStructure":{"carSerial":null,"carValue":"0","chasisSerial":null,"classificationType":{"code":"P","description":"PESADO"},"color":{"code":"0004","description":"GIALLINO"},"colorOther":null,"dateLastCRAcquisition":"2021-02-26T00:00:00.000+00:00","dateLastTransfeFROM":"2000-03-06T00:00:00.000+00:00","dateLastTransfer":"2000-03-06T00:00:00.000+00:00","dateLastTransferTO":null,"dateLastUpdate":"2011-12-23T00:00:00.000+00:00","dateStartValidity":"2011-12-23T00:00:00.000+00:00","fuelDescription":"N/A","mark":{"code":"0847","description":"IVECO"},"model":{"code":"016174","description":"59.12"},"motorSerial":"2127753","plate":"RS4457","plateCheck":"2","type":{"code":"0014","description":"CHASSIS"},"yearManufacture":"1998"}
                            }]
                        },
                        "detailOwners":{
                            "detailOwner":[]
                        },
                        "resumeCar":{
                            "dateLastCRAcquisition":null,
                            "flagActualOwner":null,
                            "presenceOfDetails":null,
                            "totalNumberOwners":null,
                            "vehicleStructure":{
                                "carSerial":null,
                                "carValue":null,
                                "chasisSerial":null,
                                "classificationType":{
                                    "code":null,
                                    "description":null
                                },
                                "color":{
                                    "code":null,
                                    "description":null
                                },
                                "colorOther":null,
                                "dateLastCRAcquisition":null,
                                "dateLastTransfeFROM":null,
                                "dateLastTransfer":null,
                                "dateLastTransferTO":null,
                                "dateLastUpdate":null,
                                "dateStartValidity":null,
                                "fuelDescription":null,
                                "mark":{
                                    "code":null,
                                    "description":null
                                },
                                "model":{
                                    "code":null,
                                    "description":null
                                },
                                "motorSerial":null,
                                "plate":null,
                                "plateCheck":null,
                                "type":{
                                    "code":null,
                                    "description":null
                                },
                                "yearManufacture":null
                            }
                        },
                        "resumeOwner":{
                            "dateLastCRAcquisition":"2021-02-26T00:00:00.000+00:00",
                            "flagHistorical":"N",
                            "owner":{
                                "fatherSurname":null,
                                "motherSurname":null,
                                "name":null,
                                "rut":null,
                                "tradeName":null,
                                "typeId":null
                            },
                            "presenceOfDetails":"S",
                            "totalAmountHeavyCars":"0",
                            "totalAmountLightCars":"0",
                            "totalAmountOtherCars":"0",
                            "totalNumberCars":"5",
                            "totalNumberHeavyCars":"4",
                            "totalNumberLightCars":"1",
                            "totalNumberOtherCars":"0"
                        },
                        "totalNumberCars":"5",
                        "totalNumberHeavyCars":"4",
                        "totalNumberLightCars":"1",
                        "totalNumberOtherCars":"0"
                    }
                }
            },
            "lanzamientosData":{
                "detailLanzamiento":{
                    "lanzamientosTemp":[]
                },"summaryLanzamiento":{
                    "courtLastLanzamiento":null,
                    "dateLastLanzamiento":null,
                    "lastJudgmentCase":null,
                    "lastLanzamiento":null,
                    "roleLastLanzamient":null,
                    "totalLanzamientos":null
                }
            },
            "transactionInfo":{
                "transactionID":"01",
                "transactionTime":null
            }
        }
    }
}